#!/usr/bin/env bash

# ################# #
# -=- Autostart -=- #
# ################# #

# // Necessary //

# Bar
"$HOME"/.config/polybar/launch &

# Xresources
xrdb merge "$HOME"/.Xresources &

# Wallpaper
"$HOME"/.fehbg &

# Notification
killall -q dunst
dunst &

# Compositor
picom &

# Autolock
xss-lock -- "$HOME"/.config/bspwm/bin/lockscreen &

# MPD
mpd &

# // Other //

# Network Manager Applet
# nm-applet &

# Polkit
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Ibus daemon
# ibus-daemon -drx &

# Fcitx5
# fcitx5 &

# Bluetooth
# blueberry-tray &
