#!/usr/bin/env bash

# ################# #
# -=- Autostart -=- #
# ################# #

# Bar
"$HOME"/.config/polybar/launch &

# Xresources
xrdb merge "$HOME"/.Xresources &

# Wallpaper
"$HOME"/.fehbg &

# Notification
killall -q dunst
dunst &

# Compositor
picom &

# Autolock
xss-lock -- "$HOME"/.config/bspwm/bin/lockscreen &

# MPD
mpd &
