#!/usr/bin/env bash

# autostart

# polybar
"$HOME"/.config/polybar/launch &

# xresources
xrdb merge "$HOME"/.Xresources &

# wallpaper
"$HOME"/.fehbg &

# notification
killall -q dunst
dunst &

# compositor
picom &

# autolock
xss-lock -- "$HOME"/.config/bspwm/bin/lockscreen &

# mpd
mpd &
