#!/usr/bin/env bash

# #################### #
# -=- BSPWM Config -=- #
# #################### #

# // Workspaces //
for monitor in $(xrandr -q | grep -w 'connected' | cut -d' ' -f1); do
		bspc monitor "$monitor" -d '1' '2' '3' '4' '5' '6' '7'
done

# // Config //
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config window_gap 5
bspc config border_width 4
bspc config focus_follows_pointer true
bspc config split_ratio 0.5
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
