#!/usr/bin/env bash

wid=$1
class=$2
instance=$3
consequences=$4

result() {
    eval "$consequences"
    [ "$state" ] || echo "$1"
}

case "$class" in
    float)
        result "state=floating center=on"
    ;;
    Pavucontrol)
        result "state=floating center=on"
        ;;
esac
