#!/usr/bin/env bash

# // Bootstrap config files //
"$HOME"/.screenlayout/monitor.sh &
"$HOME"/.screenlayout/monitor.sh &
"$HOME"/.config/bspwm/config/cfg &
"$HOME"/.config/bspwm/config/rules &
"$HOME"/.config/bspwm/config/autostart & 
"$HOME"/.config/bspwm/config/decoration & 
"$HOME"/.config/bspwm/config/misc &
