#!/usr/bin/env bash

# penguinRice: p3nguin-kun's auto rice script

# terminate already running programs
processes=("sxhkd" "polybar" "dunst")
for process in "${processes[@]}"; do
    if pgrep -f "$process"; then
        killall -q "$process"
    fi
done

# start sxhkd: keybind daemon
sxhkd -c "$HOME"/.config/bspwm/config/keys &

# config files
"$HOME"/.screenlayout/monitor.sh &
"$HOME"/.config/bspwm/config/init &
bspc config external_rules_command "$HOME"/.config/bspwm/config/external-rules &

# user's config
"$HOME"/.config/bspwm/user/init &
