#!/usr/bin/env bash

run() {
	if ! pgrep -f "$1" ; then
		"$@"&
	fi
}

# user specific autostart
# usage: run [command]

# Network Manager Applet
# run nm-applet

# Ibus daemon
# run ibus-daemon -drx

# Fcitx5
# run fcitx5

# Bluetooth
# run blueberry-tray

# Syncthing
# run syncthing --no-browser
