#!/usr/bin/env bash

# user specific options

# current colorscheme
bsp_color=macaroni

# gaps (default: 6)
bsp_gaps=6

# window border (default: 4)
bsp_border=4

# split ratio (default: 0.5)
bsp_split_ratio=0.5

# padding (default: 0)
bsp_top_padding=0
bsp_bottom_padding=0
bsp_left_padding=0
bsp_right_padding=0

# focus follow pointer (default: true)
bsp_focus_pointer=true

# borderless monocle (default: true)
bsp_borderless_monocle=true

# gapless monocle (default: false)
bsp_gapless_monocle=false
